-- Usuario de prueba (ADMIN)
INSERT INTO Usuario(id, email, password, rol, activo, nombre, apellido, dni,
                    pais, provincia, ciudad, direccion, cp, telefono)
VALUES(null,
       'test@unlam.edu.ar',
       'test',
       'ADMIN',
       true,
       'UNLaM',
       'Admin',
       '11222333',
       'Argentina',
       'Buenos Aires',
       'La Matanza',
       'Florencio Varela 1903',
       '1754',
       44808900),
      (null,
       'test_test@unlam.edu.ar',
       'test_test',
       'TEST',
       true,
       'UNLaM',
       'Admin',
       '11222333',
       'Argentina',
       'Buenos Aires',
       'La Matanza',
       'Florencio Varela 1903',
       '1754',
       44808900);
